name: RHub Check

on:
  # Triggers the workflow on push to the main branch and on pull requests
  push:
    branches:
      - main
  pull_request:
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  rhub-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'

      # Install rhubv2
      - name: Install rhubv2
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_github("r-hub/rhubv2")'

      # Run the rhub check
      - name: Run rhub check
        run: |
          cat <<EOF > rhub.yaml
          version: 2
          tasks:
            - name: "Check on r-devel-linux-x86_64-debian-clang"
              platform: r-devel-linux-x86_64-debian-clang
              timeout: 3600
              env:
                _R_CHECK_FORCE_SUGGESTS_: false
                _R_CHECK_CRAN_INCOMING_: true
              skip:
                examples: false
                tests: false
                vignettes: false
              options:
                manual: false
                build_vignettes: true
              rcmdcheck_args: []
              extra_packages:
                - Rcpp
                - dplyr
                - ggplot2
              scripts:
                before: []
                after: []
          EOF
          Rscript -e 'library(rhubv2); rhubv2::check_with_yaml()'
